---
- name : Enable and sync with systemd-timesyncd
  hosts: all
  become: yes
  tasks:
    - name: copy module 1st line
      copy:
        dest: /etc/systemd/timesyncd.conf
        content: 'NTP=10.0.25.8\n'
    - name: set timezone to Asia/Manila
      timezone:
        name: Asia/Manila
    - name : Get timesyncd status
      command: /usr/bin/systemctl is-active systemd-timesyncd.service
      ignore_errors: yes
      register: result

    - name: Start and enable systemd-timesyncd
      service:
        name: systemd-timesyncd.service
        state: restarted
      when: result.rc == 0 
    
    - name: Start and enable open-vm-tools
      apt:
        name: open-vm-tools
        state: latest 
