---
- hosts: all
  become: yes
  vars:
    users:
    - username: "sshbally"

  tasks:

  - name: Adding User {{ item.username }}
    user:
      name: "{{ item.username }}"
      create_home: yes
      comment: "Created with Ansible by PRCM"
      password: "{{ 'Solaire_2021_ssh' | password_hash('sha512') }}"
      update_password: on_create
      groups: sudo
      shell: /bin/bash
    with_items: "{{ users }}"
