---
- hosts: all
  become: yes
  vars:
    users:
    - username: "sshkong"
    - username: "sshokta"

  tasks:

  - name: Adding User {{ item.username }}
    user:
      name: "{{ item.username }}"
      create_home: yes
      comment: "Created with Ansible by PRCM"
      passwd: "{{ 'Solaire_2021_ssh' | password_hash('sha512') }}"
      update_password: on_create
      groups: sudo
    with_items: "{{ users }}"
